- README.md
- manifests/eyaml.pp
- manifests/init.pp
- manifests/params.pp
managing the keys files. Adding a default owner and group for file
resources in eyaml.pp to reduce duplication.
> Adding an option to disable creating keys when enabling hiera-eyaml and

- README.md
- manifests/init.pp
This also brings the parameters in the README up to date. It also removes the parameter documentation from init.pp, as it's already in README.
> Reformat parameters in README to be more readable

- manifests/init.pp
This introduces dependency to puppetlabs/stdlib module
> Validate the values of $merge_behavior

- CHANGELOG.md
- README.md
- manifests/eyaml.pp
- manifests/params.pp
Rebase and readme update for #45. We still need to solve the following issue:
> This adds pe_puppetserver_gem to the provider for PE 3.7 in params, for hiera-eyaml installation. I do have a bit of a conundrum as a fresh install doesn't work until pe-puppetserver is restarted. BUT restarting pe-puppetserver in code could cause cascading failures for end users due to JVM startup time. Does anyone have thoughts on this? Should we just leave this out for now and just add documentation that JVM needs to be restarted? Or do we wait for things down the line that will fix this issue?
> Terrimonster fix 37 prov

- README.md
The README file has a typo where it lists the parameters to the main class.  It says "backend" but that should be plural.  This commit fixes it.
> Fix typo in backends parameter name.

- README.md
This PR fixes a minor typo in the README file which resulted in a long link being shown.
> Fixing broken markdown link

- manifests/init.pp
- manifests/params.pp
- metadata.json
This PR adds Puppet 4 AIO paths and providers to `params.pp`.
> Support AIO Puppet 4

- manifests/init.pp
- metadata.json
- templates/hiera.yaml.erb
It would match documentation, make redundant code unnecessary and solve #61 
also, since hiera::params is using str2bool function, module is dependent on stdlib
> make 'eyaml_datair' same as 'datadir' by default

- manifests/params.pp
The default owner/group in Puppet Enterprise 2015.2.0 still need to be pe-puppet, because puppet is not a valid user/group. This commit adds logic to check the $pe_server_version fact to determine whether the server is PE or opensource, and set the default owner/group accordingly.
> Add default compatibility with PE 2015.2.0

- templates/hiera.yaml.erb
This is a style commit intended to clean up the YAML output of the
hiera.yaml.erb template for easier presentation.
- Eliminates redundant newlines. If a parameter is undef or empty,
there need not be a blank newline holding its place. Style changes
to put formatting newlines into the conditional that places the
parameter, so that they are not included if the parameter is not used.
- Consistent indenting. Use two-space indents, use indents in
hierarchy array.
- Consistent spacing. Use a space between all keys or no keys. This
commit adds a space between all keys.
Example:
````puppet
class { 'hiera':
datadir_manage => false,
notify         => Service['pe-puppetserver'],
hierarchy      => [
'nodes/%{clientcert}',
'environment/%{environment}',
'datacenter/%{datacenter}', …
```
> Clean up style of hiera.yaml.erb template

- manifests/init.pp
- manifests/params.pp
Puppet master needs to be restarted in order for hiera configuration changes to take effect
> restart puppet master

- Gemfile
- manifests/eyaml.pp
- manifests/params.pp
- spec/acceptance/hiera_spec.rb
- spec/acceptance/nodesets/pe-redhat-7-vcloud.yml
- spec/acceptance/nodesets/pe-ubuntu-1404-vcloud.yml
- spec/acceptance/nodesets/redhat-7-vcloud.yml
- spec/acceptance/nodesets/ubuntu-1404-vcloud.yml
- spec/classes/hiera_spec.rb
- spec/spec_helper_acceptance.rb
- templates/hiera.yaml.erb
This PE stuff is confusing.
This should fix the hiera-eyaml installation on PE 2015.2. It also fixes
a bug with versioncmp() trying to compare $::pe_server_version when it
is undef to determine if it's on PE or FOSS puppetserver.
It also updates the formatting of hiera.yaml to be a bit more
consistent across puppet versions (thanks zaml for being not like yaml).
This adds beaker tests that should work on foss puppet 3, PE 3, and
PE 2015.2+puppet-agent packaging.
Rework of #77
> Fixing 2015.2 handling

- README.md
- manifests/init.pp
Recently I have used this module in deploying a development environment as a non-root user (puppet apply) for local users in their homedirectory using ~/.puppet/hiera.yaml as a config file - this worked fine apart from the fact that the module always wants to create /etc/hiera.yaml.
This PR makes it possible to turn this feature off, default is true so there is no breaking change here.
> Added option to switch on/off the creation of the /etc/hiera.yaml

- manifests/params.pp
Discovered by @bwilcox, the versioncmp() function expects strings so
undef variables cause issues. This patch shortcuts the logic to only
versioncmp defined variables.
Closes #94
> Only pass strings to versioncmp

- manifests/init.pp
I needed to override the provider when I wanted to include hiera-eyaml because I'm using puppetserver.
> Add provider to class parameters

- .fixtures.yml
- CHANGELOG.md
- Gemfile
- README.md
- manifests/eyaml.pp
- manifests/init.pp
- manifests/params.pp
- metadata.json
- spec/acceptance/hiera_spec.rb
- spec/classes/hiera_spec.rb
- spec/spec_helper_acceptance.rb
- templates/hiera.yaml.erb
Some day I will get this right.
It looks like leaving the keys/ directory and hiera.yaml in the codedir
on recent puppet versions causes issues. Also the datadir default needs
to change on recent versions of puppet. So a major release is needed :(
> Update logic for PE 2015.x (again)

- spec/acceptance/hiera_spec.rb
This package doesn't actually exist, so causes tests to fail.
> Remove custom eyaml package from test

- manifests/init.pp
- spec/classes/hiera_spec.rb
- templates/hiera.yaml.erb
This commit adds two new optional parameters.
These are eyaml_pkcs7_public_key and eyaml_pkcs7_private_key.
If specified, the values will be used in the generated hiera.yaml file.
If not given, behaviour remains unchanged and the keys are assumed to be
in the 'keysdir' directory.
This change allows more complicated hiera eyaml configuration.  For
example, my current manually configured hiera.yaml contains...
```
:eyaml:
:pkcs7_private_key: /etc/puppet/keys/%{::product}/private_key.pkcs7.pem
:pkcs7_public_key:  /etc/puppet/keys/public/%{::product}_key.pkcs7.pem
```
I have multiple sets of keys, (one pair per 'product'), and the private
and public keys aren't in the same directory.
> Add new eyaml_pkcs7_public/private_key params

- manifests/install.pp
Applied to live system and the change works.
> Fix issue where find returns exit code 0 regardless of a regex match

- spec/classes/hiera_spec.rb
- templates/hiera.yaml.erb
`to_yaml` produced different output based on both ruby and puppet
version.  With this change, any hierarchy line containing a `%` is
always surrounded by double quotes.  This matches the formatting shown
in the README.
https://github.com/voxpupuli/puppet-hiera#beginning-with-hiera
> Replace `to_yaml` in hiera.yaml template

- CHANGELOG.md
- README.md
- unlike previous versions, tag has a leading 'v', i.e. v2.1.0
- module installs deep_merge gem automatically
- according to documentation one would almost never use 'deep' merge behavior, use more widely used 'deeper' as an example
- puppet server is correctly restarted when gems are installed
> documentation updates for version 2.1.0

- metadata.json
On puppet3.8 there are dependency errors listed due to the use of hyphens rather than forward slashes in the metadata.json file:
```
root@testbox:/etc/puppet/modules/hiera# puppet module list
Warning: Missing dependency 'puppetlabs-inifile':
'hunner-hiera' (v2.0.1) requires 'puppetlabs-inifile' (>= 1.0.0 < 2.0.0)
Warning: Missing dependency 'puppetlabs-stdlib':
'hunner-hiera' (v2.0.1) requires 'puppetlabs-stdlib' (>= 4.3.1 < 5.0.0)
/etc/puppet/modules
├── hunner-hiera (v2.0.1)
├── puppetlabs-inifile (v1.5.0)
└── puppetlabs-stdlib (v4.12.0)
```
Altering the hyphens to forward slashes resolves this:
```
root@stackstorm:/etc/puppet/modules/hiera# puppet module list
/etc/puppet/modules
├── hunner-hiera (v2.0.1)
├── puppetlabs-inifile (v1.5.0)
└── puppetlabs-stdlib (v4.12.0)
```
I know that …
> Update metadata.json to not give dependency errors in puppet3.8

- .rubocop.yml
- CHANGELOG.md
- README.md
- Rakefile
- manifests/init.pp
- spec/classes/hiera_spec.rb
- templates/hiera.yaml.erb
* previously this module only allowed for configuration of
eyaml and yaml backend types.  So any time a new backend
was used the user was forced to abandon this module and
fork the code to accommodate their special backend.
This commit fixes the issue by allowing the user to pass
in a hash of backend configuration data for not only yaml
and eyaml but also any other backend type.
This change maintains backwards compatibility with previous versions
and allows the user to supply additional backends very easily.
> Fixes #153 - Add support for 3rd party backends

- spec/classes/hiera_spec.rb
Added spec test to see what happens when eyaml is unspecified (defaults to false) and eyaml_gpg is true.
> Test when eyaml_gpg is true and eyaml is unspecified

- manifests/init.pp
- spec/classes/hiera_spec.rb
older versions of this module had eyaml listed as the first
backend. people who use eyaml need eyaml as the first back end,
otherwise the encrypted valued will be read in as plain yaml and never
decrypted.
ref https://github.com/voxpupuli/puppet-hiera/issues/161
> make eyaml be the first backend

- manifests/eyaml_gpg.pp
Puppet will translate the mode of 0600 to 0700 for the directory,
not the other way around.
> Do not make files in the gnupg home executable.

- templates/hiera.yaml.erb
The `deep_merge_options` parameter should be respected when `merge_behavior => 'deeper'`, especially since 'deeper' is really the only useful of the two non-native behavior options (see https://docs.puppet.com/hiera/3.2/configuring.html#mergebehavior).
> Support deep_merge_options with 'deeper' merge_behavior

- templates/hiera.yaml.erb
merge_behaviour (British English) vs merge_behavior (American English). Sadly this isn't the first time I've fallen for that when working with Hiera :(
> Correct spelling of @merge_behavior in template

- manifests/params.pp
- spec/classes/hiera_spec.rb
https://blog.yo61.com/test-for-undefined-fact-in-puppet-with-strict_variables
`getvar()` has better compatibility that `defined()` which is broken in
early puppet 3 versions.
After migrating the module to puppet 4, we will then be able to use the
facts hash instead.
Fixes #GH-171
> Strict variables fix for `pe_server_version`

- .fixtures.yml
- README.md
- manifests/init.pp
- manifests/install.pp
- spec/defines/install_spec.rb
Useful for those trying to install gems via a proxy server.
fixes #GH-187
> Add gem_install_options parameter

- README.md
New version of PE (2017.3.1 in my situation) still need puppetlabs-puppetserver_gem
as a hidden dependancy. This updates the README stating that this is the
case for more than just 2015.x.
> Update Setup Requirements

- manifests/init.pp
- spec/classes/hiera_spec.rb
The following seems not being applied:
- #the requested_backends has a side affect in that the eyaml will always be
- #first for backend lookups.  This can be fixed by specifing the order in
- #the backends parameter ie. ['yaml', 'eyaml', 'redis']
When we specify an order:
```yaml
hiera::backends:
- consul
- eyaml
- yaml
```
eyaml is always included as first and the hiera.yaml generated comes as:
```yaml
:backends:
- eyaml
- consul
- yaml
``` 
The fix applied was to ignore the concat if eyaml is already present in the user defined backends.
> Fix side affect in that the eyaml will always be first for backend lookups

- README.md
Trying to make this less confusing since Puppet Open Source these days (using 6.0 myself) seems to use the same paths as Puppet Enterprise.
> README.md: remove some obsolete Puppet Open Source default values

- README.md
This note should have been removed with commit bc3b1ccbb8908c1ea823aaf05da804ded072ad69, which dropped Puppet 3 support.
> README.md: remove note about FOSS Puppet 3 default

- README.md
The default was changed in commit 650f144335d2e08cf93cf43139c25be2784ddc9b but README.md was not updated.
> README.md: correct default of hiera5_defaults

- manifests/init.pp
If $hiera_yaml already exists as a symbolic link on a target system the puppet run will not replace this link with a file. Anyway in my opinion there's no reason why this file resource is set to "ensure => present" instead of "ensure => file". So, I replaced it with file.
> Change hiera_yaml to ensure file

- types/hiera5_defaults.pp
https://puppet.com/docs/puppet/5.3/hiera_config_yaml_5.html#backend-key
> Used for any hierarchy level that doesn't specify its own. This must be one of:
> * data_hash - produces a hash of key-value pairs (typically from a data file)
> * lookup_key - produces values key by key (typically for a custom backend)
> * data_dig - produces values key by key (for more advanced backends)
> * hiera3_backend - global layer only
> Make `data_hash` in `hiera5_defaults` optional

- manifests/eyaml.pp
- manifests/eyaml_gpg.pp
- manifests/init.pp
- manifests/params.pp
Fixes #245 
Replaces #246 
Sets better defaults for `/etc/hiera.yaml`, eyaml keys, etc., to prevent conflict with the latest Puppet Enterprise versions.
> Hiera file permission updates

- manifests/init.pp
- manifests/params.pp
- spec/acceptance/hiera_spec.rb
- spec/classes/hiera_spec.rb
- Puppet: ANY
- Ruby: ANY
- Distribution: ANY
- Module version: 3.4.1
`puppet agent -t` :cat: 
file permissions being set to 0644
let the user assign different permissions. I do have Redis token and Hashicorp Vault token set in hiera.yaml
> hiera.yaml is word readable. Allow setting different permissions to hide secrets

- spec/classes/hiera_spec.rb
- templates/hiera.yaml.epp
Plugins like hiera_vault have option values that are themself hashes. Currently the template will simply write this down as a string value, which leads to a broken configuration.
The implementation in this PR uses the fact that JSON is a valid subset of YAML. This may not look pretty as everything ends up on the same line, but it will always be valid.
I'm also not sure if it would be better to use the same methods if the value is an array, which could hold hashes as values as well and that isn't really handled correctly at the moment.
Let me know what you think.
> Format options value as json if it is a hash

- README.md
- manifests/eyaml.pp
- manifests/eyaml_gpg.pp
- manifests/init.pp
- manifests/install.pp
- manifests/params.pp
- spec/classes/deep_merge_spec.rb
- spec/classes/eyaml_gpg_spec.rb
- spec/classes/hiera_spec.rb
When puppet runs it gets an error that it can't handle sockets. Since gpg-agent is integral to gpg now,
that is an error that is unavoidable with thee current setup.
If you do this manually, ie. `chmod -r 0600 $GNUPGHOME`, then there is no need to run this and get an error
every run.
> Add possibility to stop recursion on gnupghome

- spec/classes/hiera_spec.rb
- templates/hiera.yaml.epp
This is just a nit, but `omit blank lines ending in -%>` resulting in a empty line being removed from the template for hiera5
```yaml
version: 5
defaults:
datadir: /etc/puppetlabs/code/environments/%{::environment}/hieradata
hierarchy:
- name: "VDefault Hierarchy and Backend (eyaml)"
```
resulting in
```diff
--- /etc/puppetlabs/puppet/hiera.yaml	2021-10-04 18:24:50.975410368 -0700
+++ /tmp/puppet-file20211005-23697-1nj6xp3	2021-10-05 10:13:17.326377551 -0700
@@ -3,7 +3,6 @@
defaults:
datadir: /etc/puppetlabs/code/environments/%{::environment}/hieradata
hierarchy:
-
- name: "VDefault Hierarchy and Backend (eyaml)"
paths:
- "fqdn/%{::cluster}/%{::fqdn}.yaml"
```
N/A, but I'm happy to create one to reference if needed
> Remove blank newline from epp template

- metadata.json
Pull Request (PR) description
Update metadata.json to include RHEL 8 support
puppet-hiera works with rhel-8 but is not officially in the metadata as a supported OS.
> Update metadata.json to include RHEL 8 support

- README.md
I was wondering if the gpg command example should use the default gpg keys path?
> Update GPG example to match defaults

- manifests/eyaml.pp
- spec/classes/hiera_spec.rb
Before this change, if you set `hiera::eyaml_pkcs7_private_key` or `hiera::eyaml_pkcs7_public_key`, those values would only be used in `hiera.yaml`, but not in the `eyaml createkeys` exec. This commit fixes that, so that the `hiera::eyaml` class respects the key path parameters.
> `eyaml`: allow custom key paths
