voxpupuli/puppet-hiera

README.md, manifests/eyaml.pp, manifests/init.pp, manifests/params.pp
This allows custom Gem source to be used for eyaml install.
=> Added gem_source param to allow a custom Gem source used for eyaml

manifests/params.pp
Improved hiera::params to introduce support for PE v3.8.0
=> Added support for PE v3.8.0

manifests/eyaml.pp
Thanks to https://github.com/ktreese for reporting this.
=> check for eyaml_version being undef

CHANGELOG.md, metadata.json
See https://github.com/hunner/puppet-hiera/compare/1.3.2...release_1.4.0 for the diff.
=> Release 1.4.0

manifests/deep_merge.pp, manifests/init.pp, templates/hiera.yaml.erb
=> Add deep_merge support. Fixes GH-38 and GH-62

README.md, manifests/eyaml_gpg.pp, manifests/init.pp, manifests/params.pp, templates/hiera.yaml.erb
This is an updated version of PR #43
Add the ability to install/configure hiera-eyaml-gpg.
Configures needed hiera.yaml properties
Installs needed gems
Generate GPG keyring
=> adding ability to use eyaml_gpg on RHEV based systems

templates/hiera.yaml.erb
configuration line is not properly terminated
=> add end-of-line after merge_behavior

LICENSE, NOTICE, metadata.json
=> Relicense BSD-2-Clause to Apache-2.0

manifests/install.pp
=> Modify gem_source handling (Do not attempt to validate path if gem_source is an URL)

.gitignore, .msync.yml, .travis.yml, CHANGELOG.md, Gemfile, Rakefile, metadata.json
=> Modulesync 0.12.4 & Release 2.1.2

.msync.yml, .rubocop.yml, .travis.yml, Gemfile, Rakefile
=> modulesync 0.12.8

CHANGELOG.md, README.md, metadata.json
=> release for version 2.2.0

manifests/deep_merge.pp, manifests/eyaml.pp, manifests/eyaml_gpg.pp, manifests/init.pp, manifests/install.pp, spec/classes/hiera_spec.rb
=> Follow manage_package for all packages (Fixes #128)

spec/acceptance/hiera_spec.rb, spec/classes/hiera_spec.rb
=> Update to new is_expected.to syntax in favor of should

manifests/eyaml_gpg.pp, manifests/install.pp, metadata.json
=> replace validate_* calls with datatypes

.github/CONTRIBUTING.md, .gitignore, .msync.yml, .overcommit.yml, .rubocop.yml, .travis.yml, Gemfile, spec/acceptance/hiera_spec.rb, spec/acceptance/nodesets/docker/ubuntu-16.04.yml, spec/classes/hiera_spec.rb, spec/defines/install_spec.rb
=> modulesync 0.21.1

.msync.yml, .rspec_parallel, Gemfile, spec/acceptance/nodesets/archlinux-2-x64.yml
=> modulesync 0.21.3

templates/hiera.yaml.epp, types/hiera5_hierarchy.pp
It is possible to specify the datadir key for every hierarchy level.
Documentation: https://docs.puppet.com/puppet/5.1/hiera_config_yaml_5.html
=> Add datadir key for hiera5 hierarchy.

CHANGELOG.md, metadata.json
=> release 3.3.1

CHANGELOG.md, metadata.json
=> release 3.3.2

.msync.yml, .overcommit.yml, Gemfile, spec/classes/hiera_spec.rb
=> modulesync 2.0.0

.fixtures.yml, .github/CONTRIBUTING.md, .msync.yml, .travis.yml, Gemfile, manifests/install.pp, manifests/params.pp, metadata.json, spec/classes/coverage_spec.rb, spec/default_facts.yml, spec/spec_helper.rb
=> modulesync 2.2.0 and allow puppet 6.x and drop puppet 3

CHANGELOG.md, metadata.json
=> release 3.3.4

manifests/params.pp
Unfortunately I do not have write permissions on this repository. :(
=> Use $facts hash

spec/classes/hiera_spec.rb, templates/hiera.yaml.epp, types/hiera5_defaults.pp
https://github.com/voxpupuli/puppet-hiera/pull/251 with tests added.
=> Support `hiera5_defaults` `options` setting

CHANGELOG.md, metadata.json
bump version 4.0.0
- allow setting hiera.yaml permissions
- breaks ubuntu 14.04 support
Fixes #265
=> bump version 4.0.0

manifests/init.pp
=> puppet-lint: autofix

metadata.json
=> add Ubuntu 20.04 as supported OS

metadata.json
=> allow puppet < 8.x

.msync.yml, .puppet-lint.rc, Gemfile, Rakefile, spec/acceptance/hiera_spec.rb, spec/classes/deep_merge_spec.rb, spec/classes/eyaml_gpg_spec.rb, spec/classes/hiera_spec.rb, spec/defines/install_spec.rb, spec/spec_helper.rb, spec/spec_helper_acceptance.rb
=> modulesync 5.1.0

CHANGELOG.md, REFERENCE.md, metadata.json
=> release 5.0.0

metadata.json
=> Fix all dependencies must have a version_requirement

.msync.yml, Gemfile, manifests/init.pp
=> modulesync 5.4.0

metadata.json
includes: #320 #321 #322 #323 #324 #325
=> puppetlabs/inifile: Allow 6.x

metadata.json
=> Add CentOs 8 and 9 support

metadata.json
=> Add Redhat 8 and 9 support

metadata.json
=> drop EOL el7 and Debian 10

metadata.json
=> Drop EOL CentOS 8

.msync.yml, Gemfile, Rakefile, metadata.json, spec/acceptance/hiera_spec.rb, spec/spec_helper_acceptance.rb
Includes the following:
- #349
- #350
- #352
- #355
=> Acceptance tests: use `lookup` instead of `hiera` command and function
